#!/bin/sh

# 
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run this script invoking that shell by setting the SHELL
#       environment variable to point to that shell before running this script.
#       For example:
#
#           SHELL=/usr/bin/ksh ./gradlew
#
#   (2) This script points at the Java runtime's "java" command. There is no
#       way to specify a custom Java runtime.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        max_fd=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $max_fd in #(
      '' | soft) : ;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$max_fd" ||
            warn "Could not set maximum file descriptor limit to $max_fd"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the classpath 'starter' class
#   * the destination of the special JVM options (like a jar file).

set -- \
        -Dorg.gradle.appname="$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- $(
        printf '%s\n' "$XSI_START" "$@"
        printf '%s\n' "$XSI_END"
        xargs -n1 -r printf "'%s'" |
        sed -E "s/\\\\'/\\\\\\\\'/'\\\\''/gm" |
        tr '\n' ' '
    )"

# Apply any additional JVM options from GRADLE_OPTS
GRADLE_OPTS="$GRADLE_OPTS -Dorg.gradle.internal.launcher.welcomeMessageDisplayed=false"

# Add default memory options if not set in GRADLE_OPTS
if [ -z "$GRADLE_OPTS" ]; then
    GRADLE_OPTS="-Xmx2048m"
else
    # Check if memory options are already set
    if ! echo "$GRADLE_OPTS" | grep -q -- "-Xmx"; then
        GRADLE_OPTS="$GRADLE_OPTS -Xmx2048m"
    fi
fi

# Read and add any GRADLE_OPTS as JVM options
while IFS= read -r line; do
    # Skip empty lines or lines that are just whitespace
    if [ -z "$line" ] || [ -z "${line#"${line%%[! ]*}"}" ]; then
        continue
    fi
    # shellcheck disable=SC2086
    set -- $line "$@"
done <<< "$(printf '%s\n' "$GRADLE_OPTS" | xargs -n1 2>/dev/null || echo "")"

# Use the maximum available, or set MAX_FD != -1 to use that value.
if [ -z "$MAX_FD" ] || [ "$MAX_FD" = "maximum" ]; then
    MAX_FD=maximum
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the classpath 'starter' class
#   * the destination of the special JVM options (like a jar file).

# Add the destination of the special JVM options
set -- \
    -Dorg.gradle.appname="$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

# Use "xargs" to parse quoted args, preserving them.
while IFS= read -r arg; do
    # Skip empty lines
    [ -z "$arg" ] && continue
    # shellcheck disable=SC2086
    set -- "$@" "$arg"
done <<< "$({ printf '%s\n' "$GRADLE_OPTS" | xargs -n1 2>/dev/null; printf '%s\n' "$@"; } | xargs -n1)"

# Everything else is in "$@".

exec "$JAVACMD" "$@"
